update README info and update hostnetwork to netmode
erda-project/erda-release pull request #3
Opened 2021-05-07 07:12 UTC by Muzry

- update README info and update host network to net mode
- @luobily

2021-05-10 08:20 UTC, luobily requested changes

2021-05-10 08:20 UTC, luobily commented on README.md
> +# Erda Installation Tools
```suggestion
# Erda Release Tools
```

2021-05-10 08:20 UTC, luobily commented on README.md
>  - Kubernetes 1.18.8
```suggestion
- Kubernetes 1.18+
```

2021-05-10 08:20 UTC, luobily commented on README.md
> +- Helm 3.4.2
These all require a version range

2021-05-10 08:20 UTC, luobily commented on README.md
> +  - Need an SLB
delete "We recommand you use ACK Pro ( AliCloud Kubernetes Pro)"

2021-05-10 08:20 UTC, luobily commented on README.md
> +  - Need an SLB
delete "- Need an SLB"

2021-05-10 08:20 UTC, luobily commented on README.md
> +- Helm 3.4 +
The whole process should not be related to Alibaba Cloud，e.g. ACK、SLB

2021-05-10 08:20 UTC, luobily commented on README.md
>  ### Step
Divided into two steps：
1. release package;
2. erda install

2021-05-10 08:20 UTC, luobily commented on README.md
>     <SLB_IP> test-java.erda-demo.erda.io
SLB_IP -> IP

2021-05-10 08:30 UTC, Muzry commented on README.md
>     <SLB_IP> test-java.erda-demo.erda.io
Done

2021-05-10 08:30 UTC, Muzry commented on README.md
>  ### Step
Done

2021-05-10 08:30 UTC, Muzry commented on README.md
> +- Helm 3.4 +
Done

2021-05-10 08:45 UTC, Muzry commented on README.md
> +- Helm 3.4.2
There are the software versions that successfully installed Erda，I think we should inform users clearly.

2021-05-13 08:30 UTC, Muzry commented on README.md
> +   > scp package/erda-release.tar.gz root@<hostip>:/root
Done

2021-05-13 08:58 UTC, luobily approved these changes
lgtm

2021-05-13 08:58 UTC, merged